### ISSUE TITLE
Any support for iPhone 6 Plus size?

### ISSUE THREAD

**Issue by nicinabox** [PEM--/grunt-svg2storeicons#1]
[According to the HIG](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html) it's 180x180. Would you accept a PR for this missing profile?

**Comment by PEM--** [comment]
Yes of course.

**Comment by PEM--** [comment]
Thank you for your PR. Merged and updated on NPM. It's available on the v0.2.3.

**Comment by nicinabox** [comment]
Thanks!
